vmware/harbor-boshrelease

jobs/harbor/spec, jobs/harbor/templates/bin/pre-start.erb
Fixes the following issue  #15 
Signed-off-by: Kieran Robinson <krobn@allstate.com>
=> Adds the ability to enable a redirect for a given storage provider

jobs/docker/templates/bin/ctl.erb, jobs/harbor/templates/bin/pre-start.erb, packages/harbor-common/spec, src/harbor-common/notary-migration-fix.sh
=> merge 1.7 to master

jobs/harbor/templates/config/harbor.yml
the the certifcate location should be /data/cert/uaa_ca.pem
=> Change the permission of the uaa certificate

jobs/wavefront/templates/config/telegraf.config.erb
=> add cpu and memory disk usage

jobs/wavefront/templates/bin/pre-start.sh.erb
=> fix error in prestart

jobs/wavefront/templates/config/telegraf.config.erb
fix problem related to disk monitor
=> fix problem related to disk monitor

jobs/wavefront/templates/config/telegraf.config.erb
=> Fix disk usage issue

jobs/harbor/templates/config/harbor.yml
=> Fix issue in minio cert issue

jobs/harbor/templates/config/harbor.yml
=> Fix GCS upgrade failed issue

scripts/add_blobs.sh
Change harbor version to 1.8.2
=> change harbor version to latest 1.8.2

jobs/harbor/templates/config/harbor.yml
add webhook configure in harbor.yml
=> add webhook configure in harbor.yml

jobs/harbor/templates/bin/pre-start.erb.sh, jobs/harbor/templates/config/harbor.yml
change to /tmp/server.key and /tmp/server.crt
=> Change location of the server.key and server.crt for prepare

jobs/harbor/spec, jobs/harbor/templates/config/harbor.yml
=> Add log insight cfg

jobs/wavefront/templates/config/docker-compose.yml.erb
Add talegraf and proxy version
=> fix the version of telegraf and proxy

jobs/harbor/templates/config/harbor.yml
Add replication adapter list in harbor bosh release
=> Add supported replication adapter list

jobs/harbor/templates/bin/pre-start.erb.sh
There are in-container migration script which might take long time, if we do it in normal ctl start, it will expire the status check(300s), put it in pre-start script. and current timeout is set to 30 minutes.
=> 1.9 change prestart to add warmUpHarbor function

jobs/harbor/templates/bin/post-start.erb.sh, jobs/harbor/templates/config/uaa.json.erb
auth -> oauth in url
split url uaa.json
disable verify cert for uaa
=> fix uaa with saml backend issue

packages/docker/spec, scripts/add_blobs.sh
=> bump up docker version

jobs/harbor/spec, jobs/harbor/templates/bin/pre-start.erb.sh
Update spec and pre-start.erb.sh
=> Add parameter intial_delay_minutes for migration delay

jobs/harbor/spec, jobs/harbor/templates/bin/post-start.erb.sh, jobs/harbor/templates/config/uaa.json.erb
Add uaa.oidc_scope parameter to boshrelease
=> Fix issue PKS-548: Harbor SAML authentication fails to accept roles 

jobs/harbor/templates/config/uaa.json.erb
missing the tail comma in uaa.json
=> missing the tail comma

jobs/harbor/spec, jobs/harbor/templates/bin/pre-start.erb.sh
=> Fix nfs mount 1.9

src/harbor-api-testing/lib/image.go, src/harbor-api-testing/tests/suites/suite01/suite.go, src/harbor-api-testing/tests/suites/suite02/suite.go, src/harbor-api-testing/tests/suites/suite03/suite.go
Delete repo url has already changed to /api/v2.0/projects/errandsmoketest/repositories/busybox
=> Fix smoke test with 2.0

jobs/harbor/spec, jobs/harbor/templates/config/harbor.yml
Add option to disable storage redirect
=> Disable storage redirect

go.mod, src/harbor-api-testing/client/harbor_api_client.go, src/harbor-api-testing/envs/environment.go, src/harbor-api-testing/lib/image.go, src/harbor-api-testing/lib/project.go, src/harbor-api-testing/lib/system.go, src/harbor-api-testing/lib/user.go, src/harbor-api-testing/main.go, src/harbor-api-testing/models/image.go, src/harbor-api-testing/models/member.go, src/harbor-api-testing/tests/suites/base/suite.go, src/harbor-api-testing/tests/suites/suite01/run_test.go, src/harbor-api-testing/tests/suites/suite01/suite.go, src/harbor-api-testing/tests/suites/suite02/run_test.go, src/harbor-api-testing/tests/suites/suite02/suite.go, src/harbor-api-testing/tests/suites/suite03/run_test.go, src/harbor-api-testing/tests/suites/suite03/suite.go
Changes include:
Update testcase for Harbor 2.0 for url changed to /api/v2.0/xxx
Update testcase because the usage already changed
Use go mod to manage package deps
=> Move the harbor concourse test to this repo

jobs/harbor/spec, jobs/harbor/templates/bin/pre-start.erb.sh, jobs/harbor/templates/bin/properties.erb.sh, jobs/harbor/templates/config/harbor.yml
Add --with-trivy option in install command and pre-start
Add trivy option in harbor.yml
Add triv in spec
=> Add trivy option in bosh

src/harbor-api-testing/go.mod
add go mod to the harbor-api-test
=> add go mod

jobs/wavefront/templates/bin/pre-start.sh.erb, packages/wavefront/packaging, packages/wavefront/spec, scripts/add_blobs.sh
Upgrade docker version to 19.03.11 and wavefrontq/proxy to 5.7 and telegraf to 1.14.4
=> Change wavefront and telegraf version

jobs/harbor/spec
The previous 50 is too big for image replication case
=> Change the max job worker to 5

jobs/harbor/templates/bin/pre-start.erb.sh
Backup database before upgrade in case the upgrade operation failed
=> Backup database before upgrade

jobs/harbor/templates/bin/pre-start.erb.sh
Make sure the version file exist
=> 2.0 change script variable

.gitignore, src/harbor-common/harbor-backup.sh, src/harbor-common/harbor-restore.sh
Fix PKS-805: the robot account cannot login after backup/restore
=> Backup all files in /data/secret exclude  the server cert and key

jobs/harbor/templates/bin/pre-start.erb.sh, scripts/add_blobs.sh
Update the pre-start script to skip warmup when fresh install
=> Skip warmup in fresh install

jobs/wavefront/templates/config/docker-compose.yml.erb
Because the version is changed in docker images, the docker-compose file should also changed
=> Change telegraph version to 1.14 and proxy version to 5.7

src/harbor-api-testing/envs/concourse_ci.go, src/harbor-api-testing/envs/concourse_ci_ldap.go, src/harbor-api-testing/envs/environment.go, src/harbor-api-testing/tests/suites/base/suite.go, src/harbor-api-testing/tests/suites/suite01/suite.go, src/harbor-api-testing/tests/suites/suite02/suite.go
Change the docker repo from dockerhub to gcr.io
Remove the scan image test
=> change testcase dockerlimit

jobs/harbor/spec, jobs/harbor/templates/bin/pre-start.erb.sh, jobs/harbor/templates/bin/status_check.erb.sh, jobs/harbor/templates/config/harbor.yml, src/harbor-api-testing/lib/scanner.go, src/harbor-api-testing/tests/suites/suite01/suite.go
Add trivy update and githubtoken option in bosh-release
Remove clair from prepare option
=> Add trivy update and githubtoken option in bosh-release

src/utils/client.go
Signed-off-by: DQ <dengq@vmware.com>
=> Fix 400 error when upgrading with config uaa

jobs/wavefront/templates/config/docker-compose.yml.erb
Add env with -Dlog4j.formatMsgNoLookups=true to docker-compose.yml.erb
=> Fix CVE CVE-2021-44228

jobs/wavefront/templates/bin/pre-start.sh.erb, jobs/wavefront/templates/config/docker-compose.yml.erb, packages/wavefront/packaging, packages/wavefront/spec, scripts/add_blobs.sh
Rollback previous workaround and upgrade wavefront proxy to 10.11
Remove version from related filename
=> Upgrade wavefront proxy version to 10.11

jobs/wavefront/templates/config/docker-compose.yml.erb
Signed-off-by: stonezdj <stonezdj@gmail.com>
=> Upgrade wavefronthq/proxy to 10.12
